;;; init.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;      documentation. There you'll find a "Module Index" link where you'll find
;;      a comprehensive list of Doom's modules and what flags they support.

;; NOTE Move your cursor over a module's name (or its flags) and press 'K' (or
;;      'C-c c k' for non-vim users) to view its documentation. This works on
;;      flags as well (those symbols that start with a plus).
;;
;;      Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;      directory (for easy access to its source code).

(doom!

:input
;;chinese
;;japanese
;;layout

:completion
(company
 +childframe)
;;helm
;;ido
;; (ivy
;;  +icons
;;  +prescient)
(vertico
 +icons)

:ui

doom
doom-dashboard
(emoji
 +unicode
 +github)

hl-todo             ; highlight TODO/FIXME/NOTE, etc.
(ligatures
 +extra)
(modeline
 +light)
nav-flash           ; blink cursor line after big motions
(popup
 +all
 +defaults)
(vc-gutter
 +diff-hl)
workspaces
zen

deft

;;doom-quit
;;hydra
;;indent-guides     ; highlights indent columns
;;minimap           ; show a map of the code on the side
;;neotree           ; a project drawer, like NERDTree for vim
;;ophints
;;tabs
;;treemacs
;;unicode
;;vi-tilde-fringe
;;window-select     ; visually switch windows

:editor
(evil +everywhere)  ; come to the dark side, we have cookies
file-templates      ; auto-snippets for empty files
fold                ; (nigh) universal code folding
(format +onsave)    ; automated prettiness
;;god               ; run Emacs commands without modifier keys
;;lispy             ; vim for emacs-lisp, for people who don't like vim
multiple-cursors    ; editing in many places at once
;;objed             ; text object editing for the innocent
;;parinfer          ; turn emacs-lisp into python, sort of
rotate-text         ; cycle region at point between text candidates
snippets            ; my elves. They type so I don't have to
word-wrap           ; soft wrapping with language-aware indent

:emacs
(dired      ; making dired pretty [functional]
 +ranger
 +icons)
electric    ; smarter, keyword-based electric-indent
(ibuffer    ; interactive buffer management
 +icons)
(undo       ; persistent, smarter undo for your inevitable mistakes
 +tree)
vc          ; version-control and Emacs, sitting in a tree

:term
eshell
;;shell
;;term
vterm

:checkers
syntax
(spell
 +aspell
 +everywhere)
grammar

:tools
(debugger
 +lsp)
biblio
direnv
(eval
 +overlay)
gist
(lookup
 +dictionary
 +offline)
lsp
magit
make
(pass
 +auth)
pdf
taskrunner
tree-sitter

;;ansible
;;docker
;;ein
;;editorconfig      ; let someone else argue about tabs vs spaces
;;prodigy           ; FIXME managing external services & code builders
;;rgb               ; creating color strings
;;terraform         ; infrastructure as code
;;tmux              ; an API for interacting with tmux
;;upload            ; map local to remote projects via ssh/ftp

:os
(:if IS-MAC macos)  ; improve compatibility with macOS
;;tty               ; improve the terminal Emacs experience

:lang
;;agda              ; types of types of types of types...
;;beancount         ; mind the GAAP
(cc
 +lsp
 +tree-sitter)      ; C > C++ == 1 might add +lsp
;;clojure           ; java with a  emacs-lisp
;;common-lisp       ; if you've seen one emacs-lisp, you've seen them all
;;coq               ; proofs-as-programs
;;crystal           ; ruby at the speed of c
;;csharp            ; unity, .NET, and mono shenanigans
data              ; config/data formats
;; (dart
;;  +flutter
;;  +lsp)           ; paint ui and not much else
;;elixir            ; erlang done right
;;elm               ; care for a cup of TEA?
emacs-lisp          ; drown in parentheses
;;erlang            ; an elegant language for a more civilized age
;;ess               ; emacs speaks statistics
;;factor
;;faust             ; dsp, but you get to keep your soul
;;fsharp            ; ML stands for Microsoft's Language
;;fstar             ; (dependent) types and (monadic) effects and Z3
;;gdscript          ; the language you waited for
;;(go +lsp)         ; the hipster dialect
(haskell
 +lsp)              ; a language that's lazier than I am
;;hy                ; readability of scheme w/ speed of python
;;idris             ; a language you can depend on
json                ; At least it ain't XML
;;(java +meghanada) ; the poster child for carpal tunnel syndrome
;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
;;julia             ; a better, faster MATLAB
;;kotlin            ; a better, slicker Java(Script)
(latex
 +cdlatex)          ; writing papers in Emacs has never been so fun
;;lean              ; for folks with too much to prove
;;ledger            ; be audit you can be
lua                 ; one-based indices? one-based indices
markdown            ; writing docs for people to ignore
;;nim               ; python + emacs-lisp at the speed of c
(nix
 +tree-sitter)      ; I hereby declare "nix geht mehr!"
;;ocaml             ; an objective camel
(org
 +dragndrop
 +gnuplot
 +hugo
 +journal
 +noter
 +pandoc
 +passwords
 +present
 +roam2)            ; organize your plain life in plain text
;;php               ; perl's insecure younger brother
;;plantuml          ; diagrams for confusing people more
;;purescript        ; javascript, but functional
(python             ; beautiful is better than ugly
 +lsp
 +poetry
 +pyright
 +tree-sitter)
;; qt                  ; the 'cutest' gui framework ever
;;racket            ; a DSL for DSLs
;;raku              ; the artist formerly known as perl6
;;rest              ; Emacs as a REST client
;;rst               ; ReST in peace
;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
(rust
 +lsp
 +tree-sitter)      ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
;;scala             ; java, but good
;;(scheme +guile)   ; a fully conniving family of emacs-lisps
(sh                 ; she sells {ba,z,fi}sh shells on the C xor
 +fish
 +tree-sitter)
;;sml
;;solidity          ; do you need a blockchain? No.
;;swift             ; who asked for emoji variables?
;;terra             ; Earth and Moon in alignment for performance.
;;web               ; the tubes
yaml                ; JSON, but readable
;;zig               ; C, but simpler

:email
(mu4e
 +gmail
 +org)
;;notmuch
;;(wanderlust +gmail)

:app
;;calendar
;;emms
everywhere          ; *leave* Emacs!? You must be joking
;;irc               ; how neckbeards socialize
;;(rss +org)        ; emacs as an RSS reader
;;twitter           ; twitter client https://twitter.com/vnought

:config
literate
(default
  +bindings
  +smartparens)

)

(after! comp
  ;; HACK Disable native-compilation for some troublesome packages
  (mapc (doom-partial #'add-to-list 'native-comp-deferred-compilation-deny-list)
        (list "/emacs-jupyter.*\\.el\\'"
              "/evil-collection-vterm\\.el\\'"
              "/vterm\\.el\\'"
              "/with-editor\\.el\\'")))

(setq native-comp-deferred-compilation nil)
(after! (doom-packages straight)
  (setq straight--native-comp-available t))

(provide 'init)
;;; init.el ends here
